# Generated by Django 5.2.6 on 2025-12-09 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Nombre o tíutlo de la tarea', max_length=150)),
                ('descripcion', models.TextField(help_text='Descripción detallada')),
                ('completada', models.BooleanField(default=False, help_text='Estado de la tarea')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('fecha_recordatorio', models.DateTimeField(help_text='Fecha recordatorio')),
            ],
        ),
    ]
